---
- hosts: localhost
  tasks:
    - name: Copy SSH key to all hosts in inventory.
      tags: ssh, ssh_copy_id
      ansible.builtin.expect:
        command: "ssh-copy-id -o StrictHostKeyChecking=no -i {{ hostvars[item].ansible_ssh_private_key_file }} {{ hostvars[item].ansible_user }}@{{ hostvars[item].inventory_hostname }}"
        responses:
          "password:": "{{ hostvars[item].ansible_become_password }}"
      loop: "{{ groups['all'] }}"
      register: copy_id
      changed_when: "'Now try logging into the machine' in copy_id.stdout"

- hosts: all
  tasks:
    - name: Ping all hosts in inventory.
      tags: ping
      ansible.builtin.ping: