# Work in Progress!
---
- name: Deinstall Oracle Automatic Storage Manager (ASM).
  hosts: "{{ hosts | default('db_servers') }}"
  tasks:

    - name: Deinstall Grid.
      tags: grid, deinstall
      become: true
      become_user: "{{ grid_user }}"
      ansible.builtin.expect:
        command: "{{ grid_home }}/deinstall/deinstall"
        echo: true
        responses:
          Questions:
          - Specify a comma-separated list of remote nodes to cleanup: "{{ ansible_hostname }}"
          - ASM configuration was not detected in this Oracle home. Was ASM configured in this Oracle home (y|n) [n]: 'y'
          - If you want to retain the existing diskgroups or if any of the information detected is incorrect, you can modify by entering 'y'. Do you  want to modify above information (y|n) [n]: 'n'
          - Do you want to continue (y - yes, n - no)? [n]: 'y'
      register: deinstall
      #failed_when: "'Oracle Universal Installer cleanup was successful.' not in deinstall.stdout"

    - name: Remove files.
      tags: file
      ansible.builtin.file:
        path: "{{ grid_home }}"
        state: absent

    # - name: Get channel command word (ccw) value from lsdasd for use in next task.
    #   tags: install, asm
    #   ansible.builtin.shell: "lsdasd | grep {{ asm_disk_path.split('/')[-1] }} | awk '{print $1}'"
    #   register: ccw
    #   changed_when: false
    #   when: asm_disk_type == 'dasd'

    - name: Zero out oracleasm disk.
      tags: disk
      ansible.builtin.command: "dd if=/dev/zero of=/dev/oracleasm/asm{{ asm_disk_ccw.split('.')[-1] }} bs=1024k count=100"