---
- name: Check if target disk is alredy formatted to avoid accidential loss of data.
  tags: dasd, asm
  ansible.builtin.shell: "dasdview -x {{ asm.disk.path }} | grep 'format  ' | awk '{print $8}'"
  register: formatted_check
  changed_when: false

- name: Format disk, if using DASD for ASM and disk is not already formatted.
  tags: dasd, asm
  ansible.builtin.command: "dasdfmt -vpyb 4096 {{ asm.disk.path }}"
  when: "'Not formatted' in formatted_check.stdout"

- name: Check if target disk is already partitioned to avoid accidental loss of data.
  tags: dasd, asm
  ansible.builtin.shell: "lsblk -lno NAME {{ asm.disk.path }} | wc -l"
  register: part_check
  changed_when: false

- name: Create partition on dasd.
  tags: dasd, asm
  ansible.builtin.command: "fdasd {{ asm.disk.path }} -a"
  when: part_check.stdout | int - 1 == 0

- name: Make filesystem on partitioned dasd.
  tags: dasd, asm
  ansible.builtin.filesystem:
    dev: "{{ asm.disk.path }}1"
    fstype: "{{ asm.disk.fs_type }}"
    resizefs: true
    force: yes
  when: "asm.disk.path ~ '1' not in ansible_mounts | map(attribute='device') | list"

- name: Get channel command word (ccw) value from lsdasd for use in next task.
  tags: dasd, asm
  ansible.builtin.shell: "lsdasd | grep {{ asm.disk.path.split('/')[-1] }} | awk '{print $1}'"
  register: ccw
  changed_when: false

- name: Setup disks for ASM.
  tags: dasd, asm
  vars:
    ccw_num: "{{ ccw.stdout.split('.')[-1] }}"
  ansible.builtin.lineinfile:
    line: 'KERNEL=="dasd*1", SUBSYSTEM=="block", ENV{ID_PATH}=="ccw-{{ ccw.stdout }}", SYMLINK+="oracleasm/asm{{ ccw_num }}", GROUP="oinstall", OWNER="{{ asm.grid_user }}", MODE="0660"'
    path: /etc/udev/rules.d/99-udev-oracle.rules
    create: true