---

# Not ready yet, need LUN equivalent for these tasks.

- name: Format disk, if using LUNs for ASM and disk is not already formatted.
  tags: luns, asm
  ansible.builtin.command: "mkfs.{{ hostvars['db_servers'].disk.fs_type }} {{ hostvars['db_servers'].disk.path }}"
  when: 
    - hostvars['db_servers'].asm == True and 
    - hostvars['db_servers'].disk.type | lower == lun and
    - not formatted.stdout

- name: Create a partition on disk for LUNs, if using ASM.
  tags: luns, asm
  community.general.parted:
    device: "{{ hostvars['db_servers'].disk.path }}"
    part_end: "100%"
    resize: true
    state: present
  when: 
    - hostvars['db_servers'].asm == True and
    - hostvars['db_servers'].disk.type | lower == lun

- name: Setup disks, if using LUNs for ASM.
  tags: luns, asm
  vars: 
    ccw_num: "{{ ccw.stdout.split('.')[-1] | join('.') }}"
  ansible.builtin.lineinfile:
    line: ACTION=="add|change", KERNEL=="sd*1", ENV{ID_PATH}=="{{ ccw.stdout }}", SYMLINK+="oracleasm/asm{{ ccw_num }}", GROUP="oinstall",  OWNER="oracle", MODE="0660"
    path: /etc/udev/rules.d/99-udev-oracle.rules