---

- name: Find Grid.zip for next task.
  vars:
    v_maj: "{{ oracle_version.split('.')[:1] }}"
  ansible.builtin.command:
    cmd: "ls {{ hostvars['dbservers'].rpm_mount_dir }} | grep {{ v_maj }}cGrid.zip"
  register: grid.zip_file_name

- name: Unzip Grid.zip.
  vars:
    v_maj: "{{ oracle_version.split('.')[:1] }}"
    v_maj_min: "{{ oracle_version.split('.')[:2] | join('.') }}"
  ansible.builtin.unarchive:
    src: "{{ hostvars['dbservers'].rpm_mount_dir }}/oracode/{{ v_maj }}c/{{ grid.zip_file_name.stdout }}"
    dest: /u01/app/grid/{{ v_maj_min }}/ghome

- name: Find cvuqdisk RPM for next task.
  vars:
    v_maj: "{{ oracle_version.split('.')[:1] }}"
  ansible.builtin.command:
    cmd: "ls {{ hostvars['dbservers'].rpm_mount_dir }} | grep cvuqdisk-*.rpm"
  register: cvuqdisk_rpm_file_name
  
- name: Install cvuqdisk RPM.
  vars: 
    v_maj_min: "{{ oracle_version.split('.')[:2] | join('.') }}"
  ansible.builtin.dnf:
    name: "/u01/app/grid/{{ v_maj_min }}/ghome/cv/rpm/{{ cvuqdisk_rpm_file_name.stdout }}"