---

- name: Unzip Grid.zip.
  tags: pre, asm
  ansible.builtin.unarchive:
    src: "{{ asm.rpm.grid }}"
    dest: "{{ asm.grid_home }}"
    creates: "{{ asm.grid_home }}/cv"
    remote_src: true
    owner: "{{ oracle.user }}"
    group: oinstall
    mode: '0775'
 
- name: Add cvuqdisk export to root and oracle user's .bash_profile.
  tags: pre, asm
  ansible.builtin.lineinfile:
    line: "CVUQDISK_GRP=oinstall; export CVUQDISK_GRP"
    path: "{{ item }}"
  loop:
    - "/home/{{ oracle.user }}/.bash_profile"
    - "{{ ansible_user_dir }}/.bash_profile"

- name: Install cvuqdisk RPM.
  tags: pre, asm
  ansible.builtin.dnf:
    name: "{{ asm.rpm.cvuqdisk }}"
    disable_gpg_check: true

- name: Stop avahi-daemon, as recommended.
  tags: pre, asm
  ansible.builtin.service:
    name: avahi-daemon
    state: stopped
    enabled: false

- name: Disable the Zeroconf network configuration feature, as recommended.
  tags: pre, asm
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network
    backup: true
    line: "NOZEROCONF=yes"
    search_string: "NOZEROCONF="
  notify: Restart NetworkManager

- name: Configure Network Time Protocol (NTP), as recommended (1/3) - install package.
  tags: pre, asm
  ansible.builtin.package:
    name: chrony

- name: Configure Network Time Protocol (NTP), as recommended (2/3) - set firewall.
  tags: pre, asm
  ansible.posix.firewalld:
    service: ntp
    permanent: yes
    state: enabled
  notify: Reload firewall

- name: Configure Network Time Protocol (NTP), as recommended (3/3).
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    backup: true
    line: "server {{ ntp_server }} iburst"
    regexp: ^.*server.*iburst.*$
  notify: Restart chronyd

- name: Ensure all files within grid home have proper ownership.
  ansible.builtin.file:
    path: "{{ asm.grid_home }}"
    state: directory
    owner: "{{ oracle_user }}"
    group: oinstall
    recurse: true