---

- name: Find Grid.zip for next task.
  tags: pre, asm
  ansible.builtin.find:
    paths: "{{ rpm_dir }}/oracode/{{ v_maj }}c/"
    patterns: '*Grid.zip'
  register: grid_zip_file_name

- name: Unzip Grid.zip.
  tags: pre, asm
  ansible.builtin.unarchive:
    src: "{{ grid_zip_file_name.files[0].path }}"
    dest: "/u01/app/grid/{{ v_maj_min }}/ghome/"
    creates: "/u01/app/grid/{{ v_maj_min }}/ghome/cv"
    remote_src: true
    owner: oracle
    group: oinstall
    mode: '0775'

- name: Find cvuqdisk RPM for next task.
  tags: pre, asm
  ansible.builtin.find:
    paths: "/u01/app/grid/{{ v_maj_min }}/ghome/cv/rpm/"
    patterns: 'cvuqdisk-*.rpm'
  register: cvuqdisk_rpm_file_name
 
- name: Install cvuqdisk RPM.
  tags: pre, asm
  ansible.builtin.dnf:
    name: "{{ cvuqdisk_rpm_file_name.files[0].path }}"
    disable_gpg_check: true
