---

# Not ready yet, need to confirm ccw grep task.

- name: Check if target disk is alredy formatted to avoid accidential loss of data.
  ansible.builtin.command:
    cmd: lsblk -f {{ hostvars['dbservers'].disk.path }} | awk '{print $2}' | tail -n+2
    register: formatted

- name: Format disk, if using DASD for ASM and disk is not already formatted.
  ansible.builtin.command: 
    cmd: "dasdfmt -vpyb 4096 {{ hostvars['dbservers'].disk.path }}"
  when: not formatted.stdout

- name: Get channel command word (ccw) value from lsdasd for use in next task.
  ansible.builtin.command:
    cmd: "lsdasd | grep {{ hostvars['dbservers'].disk.path }} | awk '{print $2}' | tail -n+2"
  register: ccw
  when: hostvars['dbservers'].asm == True

- name: Setup disks, if using DASD for ASM.
  vars: 
    ccw_num: "{{ ccw.stdout.split('.')[-1] | join('.') }}"
  ansible.builtin.lineinfile:
    line: ACTION=="add|change", KERNEL=="dasd*1", ENV{ID_PATH}=="{{ ccw.stdout }}", SYMLINK+="oracleasm/asm{{ ccw_num }}", GROUP="oinstall",  OWNER="oracle", MODE="0660"
    path: /etc/udev/rules.d/99-udev-oracle.rules
  when: 
    - hostvars['dbservers'].asm == True and
    - hostvars['dbservers'].disk.type | lower == dasd