---
- name: Delete SSH key from known hosts if it already exists for idempotency
  tags: ssh_copy_id, ssh
  lineinfile:
    path: "~/.ssh/known_hosts"
    search_string: "{{ hostvars[localhost].ansible_host }}"
    state: absent

- name: Template expect script.
  tags: ssh_copy_id, ssh
  template:
    src: ssh-copy-id.exp.j2
    dest: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    force: yes

- name: Copy SSH ID from controller to remote host using expect script.
  tags: ssh_copy_id, ssh
  command: "expect {{ role_path }}/files/ssh-copy-id-expect-pass.exp"
  register: ssh_copy
  failed_when: "'Now try logging into the machine' not in ssh_copy.stdout"

- name: Print results of copying ssh id to remote host
  tags: ssh_copy_id, ssh
  debug:
    var: ssh_copy

- name: Delete templated expect script on controller.
  tags: ssh_copy_id, ssh
  file:
    path: "{{ role_path }}/files/ssh-copy-id-expect-pass.exp"
    state: absent