---
- name: Install tigervnc-server package.
  tags: vnc, service
  ansible.builtin.package:
    name: tigervnc-server
    state: present

- name: Install the 'Server with GUI' package group.
  tags: vnc, service
  ansible.builtin.dnf:
    name: '@Server with GUI'
    state: present

- name: Add vncserver port to firewall.
  tags: vnc, service
  ansible.posix.firewalld:
    port: 5901/tcp
    permanent: yes
    state: enabled
    zone: public
  notify: Reload firewall

- name: Add oracle user to vncserver configuration.
  tags: vnc, service
  ansible.builtin.lineinfile:
    path: /etc/tigervnc/vncserver.users
    line: ":1={{ oracle.user }}"

- name: Set use gnome for vncserver.
  tags: vnc, service
  ansible.builtin.lineinfile:
    path: /home/{{ oracle.user }}/.vnc/config
    line: "session=gnome"

- name: Create vncserver config file for oracle user.
  tags: vnc, service
  ansible.builtin.shell: "printf '{{ oracle.pass }}\n{{ oracle.pass }}\n' | vncpasswd -f > /home/{{ oracle.user }}/.vnc/passwd"
  args:
    creates: "/home/{{ oracle.user }}/.vnc/passwd"

- name: Start and enable vnc server.
  tags: vnc, service
  ansible.builtin.service:
    name: vncserver@:1
    state: started
    enabled: true